<?php

namespace Leady\Goods\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Leady\Goods\Models\Traits\BelongsToGood;
use Leady\Goods\Models\Traits\GoodsSkuCanDo;

class GoodsSku extends Model
{

    use BelongsToGood, GoodsSkuCanDo;

    protected $guarded = [];

    protected $casts   = [
        'sku' => 'json',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::deleting(function ($model) {
            $model->price()->delete();
        });
    }

    /**
     * 价格关联
     * @return mixed
     */
    public function price()
    {
        return $this->hasOne(GoodsSkuPrice::class);
    }

}
